name = "DimensionfulAngles"
uuid = "2d4b8d7a-02d9-40f9-9abe-9c695b77de0d"
authors = ["Carlos A. Michelén Ströfer <c.michelen.strofer@gmail.com> and contributors"]
version = "0.1.2"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulEquivalences = "da9c4bc3-91c8-4f02-8a40-6b990d2a7e0c"

[compat]
Unitful = "1.10"
UnitfulEquivalences = "0.2"
julia = "1.7"
